name: bia
services:
  server:
    environment:
      DB_PORT: "5432"
      DB_PWD: postgres
      DB_USER: postgres
    image: 351501490876.dkr.ecr.us-east-1.amazonaws.com/bia:cbfb8e1
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "80"
      protocol: tcp
networks:
  default:
    name: bia_default
